2021-03-07 14:23:04,394 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 14:23:04,451 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 14:23:04,506 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 14:23:04,565 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 14:41:32,960 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 14:41:32,980 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 14:41:33,019 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 14:41:33,037 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 14:41:39,145 ERROR: Exception on /login [GET] [in /hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/hdd/code/eastbournecottage/app/routes.py", line 25, in login
    return redirect(url_for('/admin'))
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/admin'. Did you mean 'admin' instead?
2021-03-07 14:41:41,726 ERROR: Exception on /login [GET] [in /hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/hdd/code/eastbournecottage/app/routes.py", line 25, in login
    return redirect(url_for('/admin'))
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/admin'. Did you mean 'admin' instead?
2021-03-07 14:41:46,747 ERROR: Exception on /login [GET] [in /hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/hdd/code/eastbournecottage/app/routes.py", line 25, in login
    return redirect(url_for('/admin'))
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/admin'. Did you mean 'admin' instead?
2021-03-07 14:42:25,157 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 14:42:25,157 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 14:42:25,209 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 14:42:25,269 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 14:51:44,702 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 14:51:44,768 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 14:51:44,783 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 14:51:44,822 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:09:01,281 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:09:01,331 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:09:01,361 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:09:01,445 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:11:44,123 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:11:44,184 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:11:44,212 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:11:44,261 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:13:00,646 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:13:00,649 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:13:00,660 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:13:00,749 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:15:07,934 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:15:08,007 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:15:08,046 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:15:08,091 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:16:34,146 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:16:34,166 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:16:34,263 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:16:34,326 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:17:28,474 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:18:43,341 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-07 19:18:43,342 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
