2021-03-28 16:29:44,574 ERROR: Exception on /get_billing_settings [POST] [in /hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2112, in make_response
    rv = jsonify(rv)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/home/anaconda3/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/anaconda3/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/anaconda3/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/home/anaconda3/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable
2021-03-28 16:32:59,545 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 16:32:59,625 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 16:32:59,639 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 16:32:59,654 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 16:33:01,259 ERROR: Exception on /get_billing_settings [POST] [in /hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/hdd/code/eastbournecottage/app/routes.py", line 564, in get_billing_settings
    'dueBy': db_first_payment.due_by.isoformat(),
AttributeError: 'NoneType' object has no attribute 'isoformat'
2021-03-28 16:40:31,642 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 16:40:31,674 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 16:40:31,716 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 16:40:31,778 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 16:42:31,098 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 16:42:31,138 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 16:42:31,181 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 16:42:31,188 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 16:46:55,746 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 16:46:55,814 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 16:46:55,891 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 16:46:55,943 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 17:01:01,116 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 17:04:03,789 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 17:04:03,810 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 17:04:03,835 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 17:04:03,889 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 17:04:05,827 ERROR: Exception on /get_billing_settings [POST] [in /hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/hdd/code/eastbournecottage/app/routes.py", line 583, in get_billing_settings
    db_check_in = db.cancellation_breakpoints.filter_by(check_in = True).first()
AttributeError: 'SQLAlchemy' object has no attribute 'cancellation_breakpoints'
2021-03-28 17:05:35,930 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 17:05:35,976 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 17:05:35,978 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 17:05:35,997 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 17:09:57,755 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 17:09:57,785 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 17:09:57,865 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 17:09:57,933 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 18:48:56,183 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 18:48:56,205 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 18:48:56,255 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-28 18:48:56,259 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-29 11:28:43,324 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-29 11:28:43,336 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-29 11:28:43,350 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-29 11:28:43,400 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-29 12:03:27,670 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-29 12:33:18,341 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-29 12:33:18,396 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-29 12:33:18,416 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-29 12:33:18,510 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-29 12:34:52,962 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-29 12:34:52,965 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-29 12:34:52,966 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-29 12:34:52,991 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
